# @BASE_URL = http://localhost:3001/api
@BASE_URL = https://reminder-express-api.herokuapp.com/api

###

GET {{BASE_URL}}/reminders

###

POST {{BASE_URL}}/reminders 
content-type: application/json

{
    "name": "Cook dinner"
}